// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TelemedicinaMonitores.Data;

#nullable disable

namespace TelemedicinaMonitores.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250702201927_InicialPaciente")]
    partial class InicialPaciente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("TelemedicinaMonitores.Models.Paciente", b =>
                {
                    b.Property<string>("MonitorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Enfermedades")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HistorialClinico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vacunas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MonitorId");

                    b.ToTable("Pacientes");
                });
#pragma warning restore 612, 618
        }
    }
}
